name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Vet source code
        run: make vet

      - name: Run unit tests
        run: make unit_test ARGS='-count=1 -coverprofile /tmp/coverage_unit_test.out'

      - name: Run integration tests
        run: make integration_test
